### ISSUE TITLE
Cannot locate scRNASeqMouseDengMonoAllelic package

### ISSUE THREAD

**Issue by Maddocent** [stephaniehicks/scBatchPaper#1]
Dear Stephanie,

Thank you for this nice work! As a teacher in Bioinformatics and Data Science, I am always  looking for illustrative examples of Reproducible Research. I came across this work after viewing Prof. Irizarry's talk during Bioc2021.  After cloning the scBatchPaper Github repo, I tried running the R code. After a minor fix to the working directories in the code, the code seems to run properly. However, I have been unsuccessful in locating an installation source for the package `{scRNASeqMouseDengMonoAllelic}`. Could you point me to a location where this package might be available. I have tried Bioconductor, Github and CRAN, but thus far no luck in finding the package.

Your help is much appreciated.
Kind regards,
Marc

**Comment by stephaniehicks** [comment]
Hi @Maddocent, thanks for your interest! Unfortunately I've changed institutions and I do not have access to the R data packages, such as the one you mentioned in the GitHub issue above. I created them for the purpose to make the data loading easy as part of the analysis. However, these packages just contained the processed data available on GEO. Hope this helps!

**Comment by Maddocent** [comment]
Dear Stephanie,

Thank you for this information. I will try to download the data directly from GEO. Too bad the referred data packages have not been published alongside the paper. That would have made reuse of the work somewhat easier.

Kind regards, and thank you for your time.

Marc


Van: Stephanie Hicks ***@***.***>
Verzonden: maandag 3 mei 2021 16:51
Aan: stephaniehicks/scBatchPaper ***@***.***>
CC: Marc Teunis ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [stephaniehicks/scBatchPaper] Cannot locate scRNASeqMouseDengMonoAllelic package (#1)


Hi @Maddocent<https://github.com/Maddocent>, thanks for your interest! Unfortunately I've changed institutions and I do not have access to the R data packages, such as the one you mentioned in the GitHub issue above. I created them for the purpose to make the data loading easy as part of the analysis. However, these packages just contained the processed data available on GEO. Hope this helps!
