### ISSUE TITLE
Adding more instructions?

### ISSUE THREAD

**Issue by Matthew1309** [stephaniehicks/scBatchPaper#2]
Hello, I came across your paper, and this tool seems pretty interesting. Unfortunately I am a bit of a noobie with R and scRNASeq. I was wondering if you could add a few technical or a guide on how to use your tool. Thank you in advance!

**Comment by stephaniehicks** [comment]
Hi @Matthew1309 -- thanks for your interest! This is not a methods / tool paper. If you're interested in the analysis of scRNA-seq data in R / Bioconductor, check out a book I helped write: 

https://bioconductor.org/books/release/OSCA

**Comment by Matthew1309** [comment]
O, okay. Thank you, I'll check it out!
